CREATE DATABASE REGIAO_BRASIL

USE REGIAO_BRASIL

CREATE TABLE REGIAO(
ID_REGIAO INT IDENTITY (1,1) NOT NULL,
REGIAO VARCHAR (50) NOT NULL,
CONSTRAINT PK_REGIAO PRIMARY KEY (ID_REGIAO),
CONSTRAINT UNICO_NOME UNIQUE(REGIAO)
);

CREATE TABLE ESTADO(
ID_ESTADO INT IDENTITY (1,1) NOT NULL,
NOME_ESTADO VARCHAR (50) NOT NULL,
ID_REGIAO INT 
CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO),
CONSTRAINT FK_ESTADO FOREIGN KEY (ID_REGIAO) 
REFERENCES REGIAO(ID_REGIAO)
);

CREATE TABLE CIDADE(
ID_CIDADE INT IDENTITY (1,1) NOT NULL,
NOME_CIDADE VARCHAR (50) NOT NULL,
POPULACAO NUMERIC (15) NOT NULL,
AREA NUMERIC (15) NOT NULL,
ID_REGIAO INT
CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE),
CONSTRAINT FK_CIDADE FOREIGN KEY (ID_REGIAO) 
REFERENCES REGIAO(ID_REGIAO)
);

INSERT INTO REGIAO (REGIAO)
VALUES ('Nordeste'), ('Sudeste'), ('Norte'), ('Sul'), ('Leste'), ('Oeste')

INSERT INTO ESTADO (NOME_ESTADO)
VALUES ('Tocantis') , ('Bahia') , ('Goías') , ('São Paulo') , ('Santa Catarina')

INSERT INTO CIDADE (NOME_CIDADE, POPULACAO, AREA)
VALUES ('Palmas' , 217.056, 2.219),
('Salvador', 2.677, 692.8),
('Goiania', 78.618, 728.8),
('São Paulo',12.180, 1521),
('Florianopolis', 477.798, 6754.4)



1- select*from REGIAO

2- select*from REGIAO , ESTADO , cidade

3- SELECT*FROM REGIAO, ESTADO, CIDADE AS DENSIDADE AS POPULACAO/AREA PERSISTED

4- SELECT*FROM ESTADO WHERE REGIAO = 'SUDESTE'

5- SELECT*FROM CIDADE WHERE NOME_CIDADE = 'São Paulo'
